### 1-Sample T-test

In [1]:
#To compare population mean and sample means if they are same or different

#Null Hypothesis says that there is no difference in mean of a population and sample.
#Alternate Hypothesis says there is difference in means of a population and sample

In [2]:
from scipy.stats import ttest_1samp,ttest_ind,norm,ttest_rel
import pandas as pd
import numpy as np

In [3]:
ages=[10,20,35,50,28,40,55,18,16,55,30,25,43,18,30,28,14,24,16,17,32,35,26,27,65,18,43,23,21,20,19,70]

In [4]:
population_mean=np.mean(ages)

In [5]:
population_mean

30.34375

In [6]:
sample_population=np.random.choice(ages,10)

In [7]:
sample_population

array([30, 23, 30, 65, 18, 24, 16, 20, 23, 20])

In [8]:
sample_mean=np.mean(sample_population)
sample_mean

26.9

In [9]:
one_sample_ttest,pvalue=ttest_1samp(sample_population,population_mean)

In [10]:
one_sample_ttest

-0.7694263435329401

In [11]:
pvalue

0.46135557443352215

In [12]:
if pvalue<=0.05:
    print('Reject Null Hypothesis.No Difference in Means ')
else:
    print('Accept Null Hypothesis.There is Difference in Means ')

Accept Null Hypothesis.There is Difference in Means 


### 2-Sample T-Test or Independent T-test

In [13]:
#NULL Hypotheses      : Means of two groups are Not same
#Alternate Hypotheses : Means of two groups are same

In [14]:
#2 Sample T-test will compare two independent means of two features to validate if both are same or different 

In [15]:
classA_Ages=np.random.randint(12,high=18,size=10)

In [16]:
classA_Ages

array([17, 14, 12, 17, 13, 12, 15, 14, 13, 16])

In [17]:
classB_Ages=np.random.randint(12,high=18,size=10)

In [18]:
classB_Ages

array([17, 15, 15, 14, 16, 16, 16, 13, 12, 13])

In [19]:
classA_Ages_mean=np.mean(classA_Ages)

In [20]:
classB_Ages_mean=np.mean(classB_Ages)

In [21]:
classA_Ages_mean

14.3

In [22]:
classB_Ages_mean

14.7

In [23]:
two_sample_t_test_stats,p_val=ttest_ind(a=classA_Ages,b=classB_Ages,equal_var =False)

In [24]:
two_sample_t_test_stats

-0.5061894487315155

In [25]:
p_val

0.6189904093635026

In [26]:
if p_val<=0.05:
    print('Reject Null Hypothesis.Means are same')
else:
    print('Do Not Reject Null Hypothesis.Means are Not same')

Do Not Reject Null Hypothesis.Means are Not same


### Paired T-test

In [27]:
#We go for paired t-test when we want to compare different means of same group taken at differnt time interval

In [28]:
weight1=[25,30,28,35,28,34,26,29,30,26,28,32,31,30,45]

In [29]:
weight2=weight1 +norm.rvs(scale=5,loc=-1.25,size=15)

In [30]:
weight1

[25, 30, 28, 35, 28, 34, 26, 29, 30, 26, 28, 32, 31, 30, 45]

In [31]:
weight2

array([24.52960561, 23.83188231, 21.88564266, 31.57268761, 22.60292559,
       31.20880647, 28.1443266 , 33.60569785, 20.80937386, 27.47027227,
       31.49986073, 27.67681776, 27.90935884, 28.43787232, 39.15093676])

### Create Data Frame

In [32]:
weights_df=pd.DataFrame({'weight1':np.array(weight1),
                         'weight2':np.array(weight2),
                         'weight_diff':np.array(weight2)-np.array(weight1)})

In [33]:
weights_df

weight1    weight2  weight_diff
0        25  24.529606    -0.470394
1        30  23.831882    -6.168118
2        28  21.885643    -6.114357
3        35  31.572688    -3.427312
4        28  22.602926    -5.397074
5        34  31.208806    -2.791194
6        26  28.144327     2.144327
7        29  33.605698     4.605698
8        30  20.809374    -9.190626
9        26  27.470272     1.470272
10       28  31.499861     3.499861
11       32  27.676818    -4.323182
12       31  27.909359    -3.090641
13       30  28.437872    -1.562128
14       45  39.150937    -5.849063

In [34]:
stats,p_val=ttest_rel(a=weight1,b=weight2)

In [35]:
stats

2.365145888204346

In [36]:
p_val

0.03299626791354203

In [37]:
if p_val<=0.05:
    print('Reject Null Hypothesis.Means are same')
else:
    print('Do Not Reject Null Hypothesis.Means are Not same')

Reject Null Hypothesis.Means are same
